# Generated by Django 5.1.1 on 2025-01-23 07:42

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticOperator',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('representative_name', models.CharField(max_length=140)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.CharField(max_length=255)),
                ('main_address', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('storage_capacity', models.IntegerField(blank=True, default=0)),
                ('explotation_capacity', models.IntegerField(blank=True, default=0)),
                ('final_disposition_capacity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RcdManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('representative_name', models.CharField(max_length=140)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.CharField(max_length=255)),
                ('main_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=140)),
                ('is_storage', models.BooleanField(default=False)),
                ('is_explotation', models.BooleanField(default=False)),
                ('is_collection_transport', models.BooleanField(default=False)),
                ('storage_capacity', models.IntegerField(blank=True, default=0)),
                ('explotation_capacity', models.IntegerField(blank=True, default=0)),
                ('final_disposition_capacity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='civilian',
            name='first_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='civilian',
            name='last_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_name',
            field=models.CharField(max_length=140),
        ),
    ]
