# Generated by Django 5.1.1 on 2025-04-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_civilian_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticoperator',
            name='temp_field',
        ),
    ]
