# Generated by Django 5.1.1 on 2025-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_logisticoperator_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticoperator',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
