# Generated by Django 5.1.1 on 2025-04-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logisticoperator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticoperator',
            name='city',
        ),
    ]
