# Generated by Django 5.1.1 on 2025-04-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_logisticoperator_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticoperator',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='logisticoperator',
            name='explotation_capacity',
        ),
        migrations.RemoveField(
            model_name='logisticoperator',
            name='final_disposition_capacity',
        ),
        migrations.RemoveField(
            model_name='logisticoperator',
            name='storage_capacity',
        ),
    ]
