# Generated by Django 5.1.1 on 2025-04-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_logisticoperator_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticoperator',
            name='main_address',
        ),
    ]
