# Generated by Django 5.1.1 on 2025-04-11 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_rcdmanager_representative_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticoperator',
            name='representative_name',
        ),
    ]
