# Generated by Django 5.1.1 on 2025-04-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_logisticoperator_representative_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
