# Generated by Django 5.1.1 on 2025-04-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_company_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='representative_id',
            field=models.IntegerField(),
        ),
    ]
