# Generated by Django 5.1.1 on 2025-05-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rcdmanager_representative_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticoperator',
            name='representative_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logisticoperator',
            name='representative_name',
            field=models.CharField(default=None, max_length=140),
            preserve_default=False,
        ),
    ]
