# Generated by Django 5.1.1 on 2025-05-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_logisticoperator_representative_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcdmanager',
            name='representative_id',
            field=models.IntegerField(),
        ),
    ]
