# Generated by Django 5.1.1 on 2025-05-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rcdmanager_representative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticoperator',
            name='representative_id',
            field=models.IntegerField(),
        ),
    ]
