# Generated by Django 5.1.1 on 2025-05-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_logisticoperator_representative_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticoperator',
            name='representative_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logisticoperator',
            name='representative_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='rcdmanager',
            name='representative_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rcdmanager',
            name='representative_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
