# Generated by Django 5.1.1 on 2025-05-20 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='control_panel.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='control_panel.project')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='control_panel.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='control_panel.project')),
            ],
        ),
    ]
