# Generated by Django 5.1.1 on 2025-05-20 02:59

import control_panel.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_alter_material_options_alter_project_owner_demand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=control_panel.models.project_photo_upload_to)),
                ('uplided_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='control_panel.project')),
            ],
        ),
    ]
